version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  groups:
    minor-actions-dependencies:
      # GitHub Actions: Only group minor and patch updates (we want to carefully review major updates)
      update-types: [ minor, patch ]

- package-ecosystem: maven
  directory: /
  schedule:
    interval: monthly
  ignore:
    # embedded-redis updates currently require Redis 7, and this project uses Redis 6
    - dependency-name: "org.signal:embedded-redis"
      versions: "[0.9,)"
  groups:
    minor-java-dependencies:
      # Java: Only group minor and patch updates (we want to carefully review major updates)
      update-types: [ minor, patch ]

- package-ecosystem: maven
  directory: /filter-cds-updates
  schedule:
    interval: monthly
  groups:
    minor-java-dependencies:
      # Java: Only group minor and patch updates (we want to carefully review major updates)
      update-types: [ minor, patch ]

- package-ecosystem: docker
  directory: /
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  schedule:
    interval: monthly
