name: Service CI

on: [push]

env:
  DOCKER_BUILD_ARGS: --cache-from type=gha --cache-to type=gha
  DOCKER_BUILDKIT: 1
  BUILDX_CONTAINER: container

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    permissions:
      packages: read
      contents: read
      id-token: write

    steps:
      - name: Checkout main project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Expose Docker environmental variables for gha cache
        # This action takes in the ID tokens etc provided by the permissions,
        # as well as some environmental data, and exposes them to future steps
        # in the correct locations and formats for their use with the `gha`
        # GitHub Actions cache for Docker.
        uses: crazy-max/ghaction-github-runtime@b3a9207c0e1ef41f4cf215303c976869d0c2c1c4 # v3.0.0

      - name: Setup Docker
        run: docker buildx create --use --name container --driver docker-container

      - name: Test C
        working-directory: c
        run: make docker_tests

      - name: Build all C
        working-directory: c
        run: make docker_all

      - name: Valgrind tests
        working-directory: c
        run: make docker_valgrinds

      - name: Set up JDK 21
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Set up necessary SGX stuff
        run: sudo ./c/docker/sgx_runtime_libraries.sh

      - name: Build and test with Maven
        run: ./mvnw -e -B verify

      - name: Build and test lambda with Maven
        working-directory: filter-cds-updates
        run: ../mvnw -e -B verify
